# Generated by Django 3.0.1 on 2020-02-02 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Energy_Kcal', models.FloatField()),
                ('Protein', models.FloatField()),
                ('Lipid_Tot', models.FloatField()),
                ('Carbohydrt', models.FloatField()),
                ('Fiber_TD', models.FloatField()),
                ('Calcium', models.FloatField()),
                ('Iron', models.FloatField()),
                ('Magnesium', models.FloatField()),
                ('Phosphorus', models.FloatField()),
                ('Potassium', models.FloatField()),
                ('Sodium', models.FloatField()),
                ('Zinc', models.FloatField()),
                ('Copper', models.FloatField()),
                ('Manganese', models.FloatField()),
                ('Selenium', models.FloatField()),
                ('Vit_C', models.FloatField()),
                ('Thiamin', models.FloatField()),
                ('Riboflavin', models.FloatField()),
                ('Niacin', models.FloatField()),
                ('Panto_Acid', models.FloatField()),
                ('Vit_B6', models.FloatField()),
                ('Folate_DFE', models.FloatField()),
                ('Choline_Tot', models.FloatField()),
                ('Vit_B12', models.FloatField()),
                ('Vit_A', models.FloatField()),
                ('Vit_E', models.FloatField()),
                ('Vit_D', models.FloatField()),
                ('Vit_D_IU', models.FloatField()),
                ('Vit_K', models.FloatField()),
                ('FA_Mono', models.FloatField()),
                ('Refuse_Pct', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.Food')),
            ],
        ),
    ]
